version: '3'

services:
  video-service:
    build: ./back-end
    volumes: 
      - ./back-end:/usr/src/app
    ports: 
      - 5001:80

  web:
    build: ./front-end
    volumes: 
      - ./front-end:/usr/local/apache2/htdocs/
    ports: 
      - 5000:80
    depends_on: 
      - video-service